# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discribe', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name=b'Date published')),
                ('Short_discribre', models.CharField(max_length=20)),
            ],
        ),
    ]
