# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktoday',
            name='Short_discribre',
            field=models.CharField(max_length=40),
        ),
    ]
